### ISSUE TITLE
runtime: Improvements for tracing

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1347]
I turned on runtime tracing, exported spans to jaeger, and find there have something hard to understand:
- action name hard to understand
- some spans have no parent(bindMount) #1395 
- disordering parent/child relationship #1389 
- delete spans not exported(or maybe exported but not saved by jaeger) #1749

This issue is used to track improvements for tracing of runtime side.

- [x] migrate from opentracing to opentelemetry(for agent compatibility) #1351
- [x] update [test script](https://github.com/kata-containers/tests/blob/main/tracing/tracing-test.sh) to check spans integrity https://github.com/kata-containers/tests/pull/3038
- [x] easy and well-documented trace collector(jaeger) configuration https://github.com/kata-containers/kata-containers/pull/1937
- [x] add sandbox ID/container ID to spans #1878 
- [x] add docs to describe how to setup Kata Containers and Jaeger https://github.com/kata-containers/kata-containers/pull/1937
- [x] define common tag schema: #1859
This may be hard to understant:

```	// Should not need to be changed (again).
	span.SetTag("source", "virtcontainers")
	span.SetTag("component", "virtcontainers")
	// Should be reset as new subsystems are entered.
	span.SetTag("subsystem", "api")
```
- [x] Pass span context from runtime to agent to get a full trace #1968

cc @jodh-intel @bergwolf 

![image](https://user-images.githubusercontent.com/1212008/106600606-9c323280-6595-11eb-843f-ed910997ffd9.png)

**Comment by fidencio** [comment]
I got to this issue while going through the open issues with the "needs-review" label.  As this is a valid enhancement request, I'm removing the "needs-review" label, and I'm adding the "area/runtime" and "area/tracing" ones.

@liubin, feel free to adjust the labels accordingly, if you notice that something is wrong.

**Comment by cmaf** [comment]
The following items
- some spans have no parent(bindMount)
- disordering parent/child relationship

are mostly fixed in https://github.com/kata-containers/kata-containers/pull/1389 with some discussion in https://github.com/kata-containers/kata-containers/issues/1504 and https://github.com/kata-containers/kata-containers/issues/1395 regarding unresolved parentless spans and an overall large number of spans respectively.

**Comment by cmaf** [comment]
I'm reviving tracing test PR [#3038](https://github.com/kata-containers/tests/pull/3038), WIP. For 2.x we currently do not have a tracing test running.

**Comment by jodh-intel** [comment]
See the [tracking project](https://github.com/orgs/kata-containers/projects/28) I've created which has further items to consider.

**Comment by cmaf** [comment]
@liubin @jodh-intel improving tracing is an ongoing project but we've covered everything in this issue, so I'm closing it. Thanks, everyone!
