### ISSUE TITLE
"Docs taskforce" tracking issue (aka review all the docs)

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#1578]
# Summary

We need to review the Kata docs in this repo (https://github.com/kata-containers/kata-containers/tree/main/docs). Ideally, this should be done yearly and before stable releases are made.

# Call to arms

If you'd like to be involved, please let us know by adding your name here or pinging us.

# What skills do you need to be involved?

An interest in improving our documentation! That's it! :smile:
(You do **not** need to be a golang/rust guru to get involved!)

# Tasks

- [x] Create a `#kata-docs` Slack channel.
- [ ] Advertise the initiative on the [public ML](http://lists.katacontainers.io/pipermail/kata-dev/).
- [ ] Remove as many old docs as possible (see https://github.com/kata-containers/kata-containers/issues/1453 - we need to remove the old 1.x install docs in this repo!)
  - [ ] Review update as much user-facing docs as possible.
  - [ ] Review all installation docs
    - [ ] AWS
    - [ ] Azure
    - [x] [CentOS -- update](https://github.com/kata-containers/kata-containers/issues/1583)
    - [x] [Fedora -- update](https://github.com/kata-containers/kata-containers/issues/1582)
    - [ ] GCE
    - [ ] minikube
    - [x] [openSUSE -- removal](https://github.com/kata-containers/kata-containers/issues/1585)
    - [x] [SUSE -- removal](https://github.com/kata-containers/kata-containers/issues/1586)
    - [x] [Snap -- update](https://github.com/kata-containers/kata-containers/issues/1601)
    - [x] [Ubuntu -- removal](https://github.com/kata-containers/kata-containers/issues/1588)
    - [ ] vexxhost
- [ ] introduce basic tests for install docs ala https://github.com/kata-containers/documentation/blob/master/.ci/test-install-https://github.com/kata-containers/documentation/blob/master/.ci/test-install-docs.sh
- [ ] Write a *new* document listing all available options, what they do, pros+cons, *etc*
  Alternatively, create a YAML file that can be used to generate both a human-readable document *and* the default config files for Kata. POC is here: https://github.com/kata-containers/kata-containers/pull/495

# See also

- https://github.com/kata-containers/kata-containers/blob/main/docs/Documentation-Requirements.md

/cc @kata-containers/architecture-committee, @egernst, @fidencio.

**Comment by fidencio** [comment]
@ariel-adam raised the question of whether we know what's the most accessed content and thanks to Sunny's reply we got to the following image:
![Captura de pantalla de 2021-04-01 19-10-04](https://user-images.githubusercontent.com/112762/113329697-2b519180-931e-11eb-9d25-ddc46c65e34c.png)

That's about the whole organization, but gives us some rough idea that, most likely, start focusing on the install guides, architecture, and developer guide is the way to go.

Also, we should also show some love to 1.x repos, at least to having them pointing our users to the 2.x repo.

**Comment by egernst** [comment]
@jodh-intel  -- should we look into re-adding https://github.com/kata-containers/documentation/blob/master/.ci/test-install-docs.sh to 2.0? I'm not sure _how_ helpful that was in catching issues, but its a gap relative to 1.x still.
