### ISSUE TITLE
CCv0 | agent: PoC for adding verify signed image support

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#2682]
### Problem

As part of the [CCv0 plan](https://docs.google.com/spreadsheets/d/1M_MijAutym4hMg8KtIye1jIDAUMUWsFCri9nq4dqGvA/edit#gid=0) we've implemented pulling and image into the Kata guest. As part of feature 1b) we want to support verifying the signature of the image, if it has been signed. This helps to validate where the container image came from and ensure that it hasn't been tampered with.

### Initial Proposal

There are a few different options we can take with the implementation of container verification, and I've listed what I can come up with in in [comment #1](https://github.com/kata-containers/kata-containers/issues/2682#issuecomment-925652415). Whilst trying to remember that this is a PoC for a limited demo, I've suggested that we split the approach into a short-term one in this issue and later follow up with a solution that integrates better with the attestation agent approach.

# Tasks
- [x] Create some test images and push them to `quay.io/kata-containers/confidential-containers`
  - [x] A busybox image that is signed and we keep the gpg key and signature for
  - [x] A busybox image that is not signed
  - [x] An nginx image that is signed, but with a different gpg key that we don't keep and signature that we do keep
- [x] Upload the extracted signature and gpg key into the kata containers git repo
- [x] Modify the build to add the signature to the default sigstore, the public gpg key and  a custom `policy.json` file that cross references the gpg key and the quay repo into the image
- [x] Modify the skopeo pull command in `rpc.rs` to use the custom policy.json with the `--policy` flag
  - [x] Basic hard-coded implementation working
  - [x] Investigate if we can move the 2-stage copy during pull image after we have built in verification
  - [x] Investigate (optionally) passing in the policy file through the agent configuration
  - [x] Check the TODOs to see if there is anything else we can tidy
- [x] Test the 4 images produce the correct results: see acceptance criteria 
- [x] Rebase the changes on the upstream kata-containers/CCv0 branch
- [x] Update the [CCv0 doc](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md) with how to use/demo this capability
- [x] Test the changes still work
- [x] Create the PR and get the community CI tests running
- [x] Merge the changes

## Acceptance Criteria

**Scenario:** Create an image bundle from a non-signed image, on an 'unprotected registry' works
**Given** I have a kata agent with a sandbox created with an image with a valid policy.json file used with gpg set up for container registry `quay.io/kata-containers/confidential-containers`
**When** I trigger the Pull image endpoint with a valid image URI from a different container registry repository that is not signed eg `registry.fedoraproject.org/fedora:latest`
**Then** I can open a shell into the sandbox and see that the image bundle has been created in `/run/kata-containers/<container-id>`

**Scenario:** Create an image bundle from a non-signed image, on a 'protected registry' is rejected
**Given** I have a kata agent with a sandbox created with an image with a valid policy.json file used with gpg set up for container registry `quay.io/kata-containers/confidential-containers`
**When** I trigger the Pull image endpoint with a valid, unsigned image URI from the `quay.io/kata-containers/confidential-containers` container registry repository `quay.io/kata-containers/confidential-containers:unsigned`
**Then** The pull image fails
  **And** The image is not unpacked and all the artifacts associated with in in `/tmp/<cid>' are removed

**Scenario:** Create an image bundle from a signed image, on a 'protected registry' succeeds
**Given** I have a kata agent with a sandbox created with an image with a valid policy.json file used with gpg set up for container registry `quay.io/kata-containers/confidential-containers`
**When** I trigger the Pull image endpoint with a valid, signed, image URI that is signed from the `quay.io/kata-containers/confidential-containers` container registry repository `quay.io/kata-containers/confidential-containers:signed`
**Then** I can open a shell into the sandbox and see that the image bundle has been created in `/run/kata-containers/<container-id>`

**Scenario:** Create an image bundle from a signed image with invalid key fails
**Given** I have a kata agent with a sandbox created with an image with a valid policy.json file used with gpg set up for container registry `quay.io/kata-containers/confidential-containers`
**When** I trigger the Pull image endpoint with a valid image URI that is signed *with a different gpg key* from the `quay.io/kata-containers/confidential-containers` container registry repository `quay.io/kata-containers/confidential-containers:other_signed`
**Then** The pull image fails
  **And** The image is not unpacked and all the artifacts associated with in in `/tmp/<cid>' are removed

**Comment by stevenhorsman** [comment]
My current thoughts are that we split this work into 2 parts: short-term and long term.

For the short-term approach I think we choose:
1. i) Up front create a gpg key pair and from them create signed and unsigned images that we can push to https://quay.io/repository/kata-containers/confidential-containers.
2. i) Check the public gpg key into the kata containers git repo and build it into the image.
3. i) Follow the approach of using the `skopeo stand-alone-verify` command and pass through the key-fingerprint as an optional field in the ImagePullRequest

Long-term once we have the attestation agent (and we know how to use it) I think the approach is different as we can use the attestation agent as a magic method to pass in everything we need (How we do that is a separate issue!):
1. Any image can be used as long as the image registry authentication method can be passed in through the attestation agent.
2. iii) The attestation agent can pass through the public key, or point to its location.
3. ii) We use the attestation agent to drive the creation of the container config documents and let the verification automatically happen. This probably means that chosen registries will always have to have signed images, but that's probably an approach we like anyway

**Comment by jiangliu** [comment]
With this proposal, all images from a protected registry must be signed, and all image from an unprotected registry must not signed. So signature is a property of registry/repository?

**Comment by stevenhorsman** [comment]
The [signature](https://www.redhat.com/en/blog/container-image-signing) signs the image including the manifest digest hash.
I'm not quite sure I understand the 2nd question - the signature is derived from the image, but you can set up configurations such that only certain repositories require signed images, which is what I'm proposing for the PoC to avoid having to configuration thousands of signature files and gpg key so we pull images. Does that make sense and answer the question?

**Comment by jiangliu** [comment]
Thanks for explanation, so the concept of 'unprotected registry' and 'protected registry' is only a convenience for the PoC, right?

**Comment by stevenhorsman** [comment]
> Thanks for explanation, so the concept of 'unprotected registry' and 'protected registry' is only a convenience for the PoC, right?

Yes - in the 'final' version I'd guess we would require all images used to be signed, but the expectation would probably be that our security conscious users would be providing their own private container registries, so hopefully the signature configuration should be straightforward

**Comment by liangzhou121** [comment]
Hi, about the Long-term with attestation agent proposal, I have three questions:
- How to pass the public key info such as KID to attestation agent? So the attestation agent can use this info to get the corresponding public key. (currently AA get layer's LEK decryption key's KID from layer's annotation)
- And where AA got the public key from? KBS? or some where else? Currently AA can build a security channel with KBS by remote attestation procedure. So AA can query the LEK's decryption key from KBS safely. So if the public key didn't store in KBS, I think we need another menchanism to ensure the public key that AA got is the expected key.
- Does the pair private key and public key are managed by PKI? Whether the public key will be issued like a certificate?

**Comment by stevenhorsman** [comment]
I guess maybe the broad question I should have asked in the long-term approach is what is the mechanism to get 'custom configuration' ie in this case potential the signature, the public gpg key, then config files that point to the public gpg key and signatures into the guests. 
I guess in these cases, unlike in keys for decryption we don't necessarily need them to be secure, but we want to trust their origin, so that a malicious attacker can't pass in their own signature, or gpg and end up with an insecure image. Maybe the AA's secure channel isn't the correct approach for this if it only deals with the KBS and instead we need some service that provides config that itself is protected by a key that the attestation agent can give keys to unlock?
Sorry that I don't have much knowledge behind my questions and suggestions!

**Comment by liangzhou121** [comment]
> I guess maybe the broad question I should have asked in the long-term approach is what is the mechanism to get 'custom configuration' ie in this case potential the signature, the public gpg key, then config files that point to the public gpg key and signatures into the guests. 

**As example: get public gpg key from AA directly for simplicity**
I think a potential simple workflow of this should be:
- Image pulling started by skopeo then skopeo send getPublicKey request to AA via GRPC. And the public gpg key's identity info should also be sent to AA simulataneously.
- After AA received the getPublicKey request, it will connect to a trust service to get the public gpg key according to key's identity info.
- Finally AA will send the public gpg key back to skopeo to verify the signature.
The trust service can be a service that is deployed in user's trust environment. 
Do you think this procedure is reasonable?

And about how to ensure AA got public key isn't tampered by other ones during communication, I think maybe have following two potential solutions:
- Use remote attestation mechanism:
    - AA generate a pair of key temporary and send the public key to trust service via remote attestation procedure.
    - The turst service will use the received public to wrap gpg public key and send it to AA.
    - AA use the temporary private key to verify the gpg public key.
- Use certificate chain:
    - The gpg public key is signed by CA and upload to the trust service as a certificate.
    - AA fetch the gpg public key(certificate) from the trust service directly and use CA's certificate to verify the certificate.

> instead we need some service that provides config that itself is protected by a **key** that the attestation agent can give keys to unlock?

What the **key** you means? Does the **key** that used to access the trust service?
Currently AA won't store any keys itself. It will only fetch needed keys from remote source dynamically according to received UnWrapKey request.

**Comment by stevenhorsman** [comment]
> **As example: get public gpg key from AA directly for simplicity** I think a potential simple workflow of this should be:
> 
> * Image pulling started by skopeo then skopeo send getPublicKey request to AA via GRPC. And the public gpg key's identity info should also be sent to AA simulataneously.
> * After AA received the getPublicKey request, it will connect to a trust service to get the public gpg key according to key's identity info.
> * Finally AA will send the public gpg key back to skopeo to verify the signature.
>   The trust service can be a service that is deployed in user's trust environment.
>   Do you think this procedure is reasonable?

This doesn't match my understanding of how the verification process works. The 'proper' way to get the container image verified on pull is to pre-create a configuration for the repository that you are pulling from which provides a link to the gpg public key on disk *and* to put the signature in a defined place - which could be on disk in the default sigstore directory, or could be on an http server, but with that approach you also need to set-up a custom properties files for the registry to point to that sigstore.
I think this means we should create the verification configuration on/soon after sandbox start-up if possible rather than it being only triggered on a pullimage request?

> What the key you means? Does the key that used to access the trust service?

Yes - there much be a mechanism to get keys via the AA otherwise it won't work with getting decrypting keys as has been discussed, this suggestion from me was based on my interpretation that you said the AA can only connect to the KBS and provide keys, not configuration data, so I suggested putting the configuration data in a separate service and the AA/KBS providing a key to give access to that. As for how that KBS and configuration service gets populated with the required data I'm not sure, but I think it is something that has to be solved, other wise we'll end up with a really secure pod sandbox that you can't configure and therefore can't do anything with.

**Comment by liangzhou121** [comment]
> I think this means we should create the verification configuration on/soon after sandbox start-up if possible rather than it being only triggered on a pullimage request?

The AA is pod level program. And I don't sure whether following scenerio is reasonable.
As example, if a user want to launch 10 containers in the pod simultaneously, and these 10 container images are all located in different repositories. 
- AA downloads all these potential configuration files and gpg public keys from 10 repositories and generate a pre-create configuration file that includes all links to gpg keys on local disk during its boot stage.
- And during image pulling stage, skopeo will select and pick up the correct gpg key according to pre-create configure file to verify the target image's signature.

Is it align with your expectation?

**Comment by stevenhorsman** [comment]
> Is it align with your expectation?

Based on my understanding of the image verification (which might not be complete), that seems to be how I'd expect it to work.

I guess an alternative to AA setting up configurations could be to have a new agent endpoint to do this, but in a Kubernetes scenario I'm not sure what would end up calling it, maybe a custom resource definition as part of the confidential-containers operator we saw yesterday?

**Comment by liangzhou121** [comment]
> Yes - there much be a mechanism to get keys via the AA otherwise it won't work with getting decrypting keys as has been discussed, this suggestion from me was based on my interpretation that you said the AA can only connect to the KBS and provide keys, not configuration data, so I suggested putting the configuration data in a separate service and the AA/KBS providing a key to give access to that. 

Sorry, maybe I make you confusion. Actually the communication protocol between KBS and AA can be extended because it's all KBS   and AA's KBC module's private protocol. So AA can fetch other data from KBS beside decryption key. 
In order to keep AA codes footprint as small as possible, AA maybe can got those configuration files and gpg public keys from KBS. So **no** new authentication mechansim should be added into AA to ensure these data weren't tampered during communication.

**Comment by liangzhou121** [comment]
> I guess an alternative to AA setting up configurations could be to have a new agent endpoint to do this, but in a Kubernetes scenario I'm not sure what would end up calling it, maybe a custom resource definition as part of the confidential-containers operator we saw yesterday?

Actually I don't sure whether it's possible to open a new agent endpoint. 
Currently AA is designed to get some global configurations data from kata agent configuration file. And we also have a issue to discuss this.  https://github.com/containers/attestation-agent/issues/6

**Comment by stevenhorsman** [comment]
I had this code working pre the Image service refactor and roots changing going in, and I've since rebased on these and I think worked out all the issues. The latest code is in https://github.com/stevenhorsman/kata-containers/tree/verify-signed-quay-image-rebase. I think it is working, so I just need to doc and tidy up and then it should be ready for a PR soon 🤞

**Comment by stevenhorsman** [comment]
Short-term issue is closed by #3023 being merged.
