### ISSUE TITLE
Look at supporting sandbox-level resource management

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#3264]
The runtime in Kata relies on hotplug of resources for “right sizing” the virtual machine based on the container workloads. today we start the VM with minimal default CPU/memory/vitrio-backend queues when we “create a sandbox”, but then augment the CPU/memory when we “create a container.” There are a couple of reasons this is handled in this fashion:

1. Pod life cycle is open ended, and at sandbox creation time, we don’t yet know the sum of container resource requirements.
2. Containers may be dynamically resized using in place Vertical Pod Autoscaling.

There are trade offs/drawbacks.

1. General code complexity.  🤷🏻 
2. Some hypervisors and hypervior+architecture combinations don’t support cpu or memory hotplug (ie, aarch64, Firecracker)
3. The virtio backend devices are sized based on the default vCPU settings for the VM, rather than what the actual workload will end up using. This can be painful, since we’ll either use a heuristic value, or just use single queue, even if the resulting pod ends up having 8 CPUs. 
4. We need to size the VM initially with enough RAM to online large amounts of hot plugged memory

With Kubernetes 1.23 (see https://github.com/kubernetes/kubernetes/pull/104886) and containerd 1.6 beta (see https://github.com/containerd/containerd/pull/6155), we now have more options. The container spec associated with the sandbox create request may contain annotations which specify the sandbox sizing requirements. In this case we could:

1. “Right size” the virtio queues based on the sandbox resources
2. “Right size” the virtual machine at boot time based on the original sandbox requirements if the configuration doesn't support resource (CPU/memory) hot plug.
3. "Right size" the virtual machine at boot time for configurations which *do* support hot plug.

(1) and (2) are straight forward and should just be done.  

(3)  Is less straightforward if we still want to support dynamic resource management for the sandbox. ie, for users that want VPA, or other scenario where containers may be added/removed. This has a couple of benefits:
 - don't need to guess on initial VM memory size to accommodate a large memory hot plug later. We can start with appropriate amount
 - fix use cases that have a hard time with memory hot plug (SPDK? -- need more details here!), including (maybe?) huge pages.
 
 How to handle this scenario, (3), is complicated, however.  ie, what to do when containers are removed from the sandbox.  
As an example, a pod spec that looks like the following:
initCtr1: cpu: 5
initCtr2: cpu: 1
ctr1 : cpu 0.5
ctr2: cpu 1.5
ctr3: cpu 2

In this case we'd received annotation indicating we require 5 CPUs for the sandbox (in this case max of init containers).
From a runtime perspective, we'd see:

create sandbox (5CPU)
  create container (5CPU)
  remove container (-5 CPU)
  create container (1CPU)
  remove container (1CPU)
  create container (0.5 CPU)
  create container (1.5 CPU)
  create container (2 CPU)
  
In the full hot plug mode, we'd remove CPUs and add CPUs after the init containers, and continually hot plug CPUs based on each workload.

In this  `static mode`, we wouldn't necessarily know that we only need 5 CPU for the init container, and that we could just remove a single CPU to meet the runtime requirement of 4 CPUs (some of ctr1, 2, 3). For configs that don't support hot plug, this is fine and simple. While we have an extra vCPU allocated, we are still constraining the sandbox on the host (cgroups) as well as in the guest (cgroups per ctr).

Similar can be observed for memory, but we should note that removing memory is much more complicated and not guaranteed for success. Allocating "too much" memory if the system is designed to scale down can be challenging, too, since the linux guest will be greedy and this memory will be used for things like page cache.

For now, it seems that tucking this behind a feature flag, like static-sandbox-mgmt, will make sense to better enable configurations that don't support hot plug, and users who desire dynamic resource mgmt should not opt into this.

Further thoughts on range of options for configs which do support hot plug, but want some form of initial sandbox sizing: 
- introduce 'static sandbox resource management flag' -- in this case we would no longer update the VM after boot (this would be noop for configurations which don't support hotplug/remove).
- don't update the sandbox (VM) size unless explicitly asked to do so (this would require API change with upper layer runtime).
- don't update sandbox (VM) size unless we see that the sum of containers in the pod are now exceeding the initial value. Do not scale down the number of vCPUs/memory)?
- don't update unless a container update is called to explicitly change the resources associated with an existing container

To break this up, some sub-issues:
- [ ] update to latest containerd to get updated annotation definition: https://github.com/kata-containers/kata-containers/issues/3276
- [ ] if annotations for sandbox sizing are present, use this for setting the virtio queue sizes: https://github.com/kata-containers/kata-containers/issues/3277
- [ ] introduce static-sandbox resource mgmt: https://github.com/kata-containers/kata-containers/issues/3278

**Comment by liubin** [comment]
@shuochen0311 this will help to resolve #3249

**Comment by egernst** [comment]
First step towards this: https://github.com/kata-containers/kata-containers/pull/2918
