### ISSUE TITLE
Update architecture document

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#3310]
List of tasks for finishing the architecture document update:

- [x] General (mega!) refresh (#3195)
- [x] Split doc into separate pieces (#3287)
- [ ] Update networking details (#3308)
- [ ] Update storage details (#3307)
- [ ] Add CRI-O details (#3309)
- [ ] Update diagrams (#3245)
- [ ] Fix broken formatting in guest assets file (#3311)
