### ISSUE TITLE
Track rust agent feature gaps

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#358]
This is a meta issue to track all feature gaps between rust-agent and go-agent.

- [x] rust-agent should support GetOOMEvent  https://github.com/kata-containers/kata-containers/issues/357
- [x] rust-agent run as init missing set hostname https://github.com/kata-containers/kata-containers/issues/355
- [x] rust-agent's debug console https://github.com/kata-containers/kata-containers/issues/354
- [x] rust-agent should support shared pid namespace https://github.com/kata-containers/kata-containers/issues/342
- [x] rust-agent cgroupv2 support https://github.com/kata-containers/kata-containers/issues/146
- [x] rust-agent: guest hook support https://github.com/kata-containers/kata-containers/issues/475
- [x] rust-agent: setupDNS for guest https://github.com/kata-containers/kata-containers/issues/689

**Comment by bergwolf** [comment]
All features are merged. Let's close it
