### ISSUE TITLE
Track runtime code cleanup

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#359]
This is a meta issue to track all runtime code cleanup works.

- [x] cleanup/remove the cli related codes #332
- [x] clean up agent abstraction #377 
- [x] clean up shim abstraction #364
- [x] drop old persistent store #368 
- [x] drop serial port and yamux, clean up proxy  abstraction #389

**Comment by liubin** [comment]
Should this issue can be closed ? @bergwolf

**Comment by bergwolf** [comment]
Yes, thanks @liubin
