### ISSUE TITLE
tracking issue for github label improvements

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#39]
We need to make better use of GitHub labels. This issue is for tracking required repo, infrastructure and process changes.

See the main PR at: https://github.com/kata-containers/tests/pull/1466.

# TODO

- [x] Land [labels database and tooling](https://github.com/kata-containers/tests/pull/1466).
- [ ] Update `github-labels.sh` to add support for setting the labels on a github repo.
  That work *might* be using a tool like [`labeler`](https://github.com/tonglil/labeler) (which supports the format of the `labels.yaml.in` on this PR). However, the `labeler` tool hasn't been updated for a while and doesn't currently support handling Label descriptions (essential), although there is an [old unmerged PR that add this support](https://github.com/tonglil/labeler/pull/37).
- [x] Apply the labels database to the least used repo (https://github.com/kata-containers/www.katacontainers.io) for testing.
  - [x] Create a new `.github` **repo** to store common GitHub metadata files (currently stored in each repos `.github/` directory): https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization
  - [x] Create a new `ISSUE_TEMPLATE.md` in the `.github` **repo** including metadata for auto-setting labels.
  - [x] Check new template works for https://github.com/kata-containers/www.katacontainers.io.
- [x] Add `needs-review`:
  - [x] To the labels db: https://github.com/kata-containers/tests/pull/1653.
  - [x] To all the issue templates in https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE.
- [x] Get consensus that "all looks good" (@egernst and @gnawux happy with labels).
- [x] Switch over to new labels:
  - [x] Apply the labels to all other repos.
  - [ ] Remove all the `.github/*` files from the other repos:
    - [ ] agent
    - [ ] ksm-throttler
    - [ ] kata-containers
    - [ ] packaging
    - [ ] proxy
    - [ ] runtime
    - [ ] shim
  - [ ] Create issue templates for the following (including labels in templates):
    - [x] bug (https://github.com/kata-containers/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
    - [x] feature (https://github.com/kata-containers/.github/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)
    - [x] enhancement (https://github.com/kata-containers/.github/blob/master/.github/ISSUE_TEMPLATE/enhancement-request.md)
    - [ ] question (needed? If so, will need to update the labels database to add the new `question` label).
  - [x] Add user documentation on labels (covered in https://github.com/kata-containers/community/pull/106).
- [x] Enable Stalebot for all repos (see ongoing discussions on this at http://lists.katacontainers.io/pipermail/kata-dev/2019-June/000870.html).
  - [x] Update [probot stale config](https://github.com/kata-containers/packaging/blob/master/.github/stale.yml) (change `P1` to `highest-priority`) (https://github.com/kata-containers/.github/pull/3).
  - [x] Add stalebot config to `.github` repo (https://github.com/kata-containers/.github/pull/3).
  - [x] Enable stalebot app in all repos (in settings).
  - [x] Remove old stalebot config (https://github.com/kata-containers/packaging/pull/557).
- [ ] Add some sort of bot / CI checks to:
  - [ ] Add `size/*` labels to PRs based on LOC test.
  - [ ] If a PR adds new code files but does not modify/add any new test files, apply the `needs-unit-tests` label.
- [ ] Add further CI checks comparing labels on issues/PRs with those in the labels db, etc.

More tasks to follow (using [probot](https://github.com/probot/probot) maybe?)

**Comment by jodh-intel** [comment]
I've now applied the new labels to https://github.com/kata-containers/www.katacontainers.io/issues/labels.

ftr, I had to patch the [`labeler`](https://github.com/tonglil/labeler) tool with https://github.com/tonglil/labeler/pull/37 like this to allow it to set a description against each label:

```sh
$ go get -u github.com/tonglil/labeler
$ cd $GOPATH/src/github.com/tonglil/labeler
$ pr=37
$ pr_branch="PR${pr}"
$ git fetch origin "refs/pull/${pr}/head:{pr_branch}"
$ git checkout "${pr_branch}"
$ go install -v ./...
```

**Comment by jodh-intel** [comment]
@egernst, @gnawux, @grahamwhaley - A couple of things:

# Enabling stalebot

We've now landed the central [stalebot](https://github.com/probot/stale) [config file](https://github.com/kata-containers/.github/blob/master/.github/stale.yml).

I'm going to hold off enabling stalebot on the repos until Monday just in case it decides to close all our PRs whilst we afk. On Monday I'll start with enabling stalebot for proxy + shim, wait and see what happens for a while and if all looks good enable for the remaining repos.

# Applying Github Labels

I've now applied them to https://github.com/kata-containers/www.katacontainers.io/issues/labels. Again, I intend to apply to all the other repos on Monday.

**Comment by jodh-intel** [comment]
Hi @ttx - we'd like to enable "stalebot" for Kata:

- https://probot.github.io/apps/stale/
- https://probot.github.io/docs/deployment/
- https://github.com/probot/stale

Do you see any issues with us doing this?

/cc @egernst, @grahamwhaley @gnawux.

**Comment by ttx** [comment]
I don't see any issue with using Probot apps, except I guess that it locks us in even deeper into GitHub (but that ship has sailed already).

The only potential issue I see is in the social function of the Stale app. In previous projects I was involved in (including Ubuntu and OpenStack), whether or not to autoclose issues has always been a hot topic. While it is convenient for developers (and reduce the need to manually review each), autoclosing generally appears as a user-hostile move, and may result in overlooking real bugs. It's generally justified when the rate of issue creation spirals out of control, but I'm not sure Kata has hit that point yet. There is no issue with marking issues "stale", but it's probably worth discussing autoclosing on the mailing-list before proceeding. I'll post similar feedback there.

**Comment by jodh-intel** [comment]
I've now applied the [new set of labels](https://github.com/kata-containers/tests/blob/master/cmd/github-labels/labels.yaml.in) to all the Kata repos.

Also raised an issue to store a copy of the old labels "just in case":

- https://github.com/kata-containers/tests/issues/1666

/cc @egernst, @gnawux.

**Comment by jodh-intel** [comment]
@egernst, @kata-containers/architecture-committee, @ttx - Now that https://github.com/kata-containers/.github/pull/6 has landed, as agreed I've just enabled ["stalebot"](https://probot.github.io/apps/stale/) for all Kata repos. Let's see how it goes...
