### ISSUE TITLE
Clean up documentation and keep it cleaned

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#40]
There are still various problems with the markdown files spread across our repos. Fix the issues and stop problems like this from re-occurring.

- [x] Fixup the broken docs in the repos:
  - [x] https://github.com/kata-containers/agent/issues/539
  - [x] https://github.com/kata-containers/ci/issues/147
  - [x] https://github.com/kata-containers/community/issues/91
  - [x] https://github.com/kata-containers/documentation/issues/433
  - [x] https://github.com/kata-containers/osbuilder/issues/278
  - [x] https://github.com/kata-containers/packaging/issues/435
  - [x] https://github.com/kata-containers/runtime/issues/1564
  - [x] https://github.com/kata-containers/tests/issues/1486
- [x] Add a CI check to avoid regressions: https://github.com/kata-containers/tests/issues/1485:
  https://github.com/kata-containers/tests/pull/1542.
- [x] Ensure all repo docs are linked to others:
  - [x] https://github.com/kata-containers/agent/issues/557
  - [x] https://github.com/kata-containers/ci/issues/160
  - [x] https://github.com/kata-containers/community/issues/99
  - [x] https://github.com/kata-containers/documentation/issues/473
  - [x] https://github.com/kata-containers/packaging/issues/501
  - [x] https://github.com/kata-containers/runtime/issues/1681
  - [x] https://github.com/kata-containers/tests/issues/1586
- [x] Update [doc requirements](https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md) doc explaining that new docs must be linked to an existing one (https://github.com/kata-containers/documentation/issues/475).
- [x] Add CI test to check that all docs in a repo are referenced: https://github.com/kata-containers/tests/issues/1588.
- [x] Fix spelling:
  - [x] https://github.com/kata-containers/agent/pull/563
  - [x] https://github.com/kata-containers/ci/pull/165
  - [x] https://github.com/kata-containers/community/pull/103
  - [x] https://github.com/kata-containers/documentation/pull/488
  - [x] https://github.com/kata-containers/ksm-throttler/pull/96
  - [x] https://github.com/kata-containers/osbuilder/pull/299
  - [x] https://github.com/kata-containers/packaging/pull/542
  - [x] https://github.com/kata-containers/runtime/pull/1735
  - [x] https://github.com/kata-containers/tests/pull/1633
- [x] [Add CI spell check test](https://github.com/kata-containers/tests/pull/1723)

**Comment by jodh-intel** [comment]
This issue can be closed when https://github.com/kata-containers/tests/pull/1542 is merged.

**Comment by jodh-intel** [comment]
We can do better - added more tasks...!

**Comment by jodh-intel** [comment]
I'm thinking that since our wikis are somewhat static, we should consider moving stable wiki content "in-tree" (move them into the repos main git tree). That would allow us to include them easily in the "ensure all docs are referenced" crusade I'm currently on.

I think the wikis tend to get overlooked since:

- The files **in** those wikis are not immediately visible when you visit the repo

- Most of our docs are in-tree so the wiki gets naturally forgotten about as users just assume all the docs will be in the same sort of areas.

- Only a few of our repos actually have the wiki feature enabled.

What do folks think? To reiterate, this would *only* be for docs we consider stable/finished so the following would not currently qualify:

- Will never be added in-tree:

  https://github.com/kata-containers/community/wiki/Review-Team-Rota

- Will eventually be added in-tree when finished:

  https://github.com/kata-containers/documentation/wiki/UserGuide

Note that in the future we can potentially add checks on wiki docs too as a repos wiki is in fact just another git repo. However, we don't have the infrastructure set up to handle those sorts of scenarios atm.

**Comment by jodh-intel** [comment]
Once https://github.com/kata-containers/tests/pull/1612 lands, this issue can be closed.

**Comment by jodh-intel** [comment]
\o/

**Comment by jodh-intel** [comment]
We need spell checking too.

**Comment by jodh-intel** [comment]
Rota doc soon to be in-tree - see https://github.com/kata-containers/community/pull/106. That just leaves the User Guide (any cycles to work on that btw @grahamwhaley?)

**Comment by jodh-intel** [comment]
Now that the [spell checker](https://github.com/kata-containers/tests/pull/1723) has landed, we can atlast close this issue!
