### ISSUE TITLE
CCv0: Refactor signature verification PoC changes to move into a test fixture

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#4111]
### Description

In the `CCv0` branch, in order to test the image signature verification PoC, I added some temporary PoC files that we wanted to get into the guest image.
The artifacts are in https://github.com/kata-containers/kata-containers/tree/CCv0/tools/osbuilder/rootfs-builder/signed-container-artifacts
and the code that added them is:
https://github.com/kata-containers/kata-containers/blob/e4bae434dea76700a4adce144657fe060045b33b/tools/osbuilder/rootfs-builder/rootfs.sh#L643-L658

In https://github.com/kata-containers/tests/pull/4677/files Wainer has added a `cp_to_guest_img` method. I think this is what we need to add in test content without polluting the code base.

### Task list

- [ ] Move the image signature verification required artefacts from https://github.com/kata-containers/kata-containers/tree/CCv0/tools/osbuilder/rootfs-builder/signed-container-artifacts into a tests repo fixtures directory (either in https://github.com/kata-containers/tests/tree/CCv0/integration/containerd/confidential/fixtures, or even better in a shared confidential directory that is used by both Kubernetes and crictl)
- [ ] In the image signature verification test add in the logic that calls `cp_to_guest_img` to copy the artifacts into the correct place in the guest image, ensuring that all the files created in `rootfs.sh` temp PoC code are put into the correct place.
  - [ ] So we can manually do dev and test on this we should create a new function in `ccv0.sh` that does the same copy operation, either driven by an environment variable, or a new command and document this in the how-to markdown file.
- [ ] Ensure that all of the code in the dev repo relating to injecting artefacts (as linked in the description) is removed.
- [ ] Make sure that all the manual and automated tests are still working
