### ISSUE TITLE
switch vendoring from dep to go modules

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#42]
The [proof-of-concept runtime PR](https://github.com/kata-containers/runtime/pull/1420) has raised a few issues for moving from [`dep`](http://github.com/golang/dep/cmd/dep) to the new [`go mod`](https://github.com/golang/go/wiki/Modules) vendoring facility.

This issue has been raised for tracking the migration path across the various repos.

# Tasks

- In the [`tests`](https://github.com/kata-containers/tests) repo:
  - [ ] Update `check_vendor()` in [`.ci/static-checks.sh`](https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh) to deal with `go.mod` files.
  - [ ] Move all `go get` calls into a function (which will do nothing for `go mod` vendoring).
- In the [`community`](https://github.com/kata-containers/tests) repo:
  - [ ] Update [vendoring document](https://github.com/kata-containers/community/blob/master/VENDORING.md) for new vendoring method.
- Switch each code repository to:
  - add `go mod` vendoring.
  - Ensure all non-golang files below `vendor/` are ignored as we do today with dep using the `non-go=true` `[prune]` option (see https://github.com/kata-containers/.github/pull/4#discussion_r289313222).
  - remove `dep` vendoring.
  - Update `.travis.yml` to remove `go_import_path` where appropriate.
  - Repos to update:
    - [ ] agent
    - [ ] ksm-throttler
    - [ ] proxy
    - [ ] runtime
    - [ ] shim
    - [ ] tests

# Timing

From https://github.com/golang/go/wiki/Modules:

> Modules are an experimental opt-in feature in Go 1.11, with the plan of incorporating feedback and finalizing the feature for Go 1.13.

This makes me wonder if we want to update our infrastructure (mostly in `tests`) to support `go mod` *alongside* supporting `dep`, but not actually switch the code repos to using `go mod` until golang 1.13 is out.

**Comment by umarcor** [comment]
@jodh-intel, thanks for opening this issue.

The main issue I found is related to the hardcoded paths in https://github.com/kata-containers/tests/blob/master/.ci/lib.sh#L30-L31. This an be found in several places, such as https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L18-L19.

> Update `check_vendor()` in [`.ci/static-checks.sh`](https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh) [](/kata-containers/tests/blob/HEAD@{2019-05-02T10:18:43Z}/.ci/static-checks.sh) to deal with `go.mod` files.

Note that this (running `dep ensure`, `go mod` or any other command in `check_vendor()`) is different from the issue with hardcoded paths.

> Move all `go get` calls into a function (which will do nothing for `go mod` vendoring).

The repositories which are not direct dependencies (such as tests) need to be explicitly downloaded still. It is possible to use `curl`, `wget` or `go get`. The point is that the locations are be different from the currently hardcoded paths.

> Update [vendoring document](https://github.com/kata-containers/community/blob/master/VENDORING.md) [](/kata-containers/community/blob/HEAD@{2019-05-02T10:18:43Z}/VENDORING.md) for new vendoring method.

In #1420 the `vendor` subdir is removed. There is no explicit vendoring.

> This makes me wonder if we want to update our infrastructure (mostly in `tests`) to support `go mod` _alongside_ supporting `dep`, but not actually switch the code repos to using `go mod` until golang 1.13 is out.

I suggest keeping the changes related to `go mod` in feature branches until you are ok with merging them into master. I don't think it is worth the effort of having both solutions coexist for a few months.

**Comment by jodh-intel** [comment]
I've updated the description on this issue, but to be clear, we need to ensure that when we switch to go modules that we continue to ignore non-golang files below `vendor/` (if that directory will even exist). This is required for correct handling of the central [`CODEOWNERS`](https://github.com/kata-containers/.github/blob/master/CODEOWNERS) file - see https://github.com/kata-containers/.github/pull/4#discussion_r289313222.
