### ISSUE TITLE
runk: implement the unimplemented features

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#4373]
@ManaSugi has created `runk` as a container runtime, it works only with some sub-commands that are not unimplemented.

This issue is used to track these unimplemented sub-commands.

- [ ] runk: support ps sub-command #4361 
- [ ] runk: support list sub-command #4362
- [ ] runk: support exec sub-command #4363
- [ ] runk: support pause/resume sub-command #4364
- [ ] runk: support update sub-command #4365
- [ ] runk: support events sub-command #4366
- [ ] runk: support init sub-command #4367
- [ ] runk: support checkpoint/restore sub-command #4368
- [ ] runk: support Systemd Cgroups #4369
- [ ] runk: support pivot_root #4370
- [ ] runk: support SELinux #4371
- [ ] runk: support Rootless #4372

**Comment by rata** [comment]
The "features" sub-command will be nice to support to.

It is becoming increasingly important for user namespace adoption to see if the OCI runtime support idmap mounts (via the features subcommand we check that). For more details, see here: https://github.com/opencontainers/runtime-spec/pull/1219. We are enforcing the OCI runtime supports idmap on containerd and crio for userns support.
