### ISSUE TITLE
Improve unit test coverage for core components

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#45]
# Overview

We need to increase our unit test (UT) coverage for the main components.

# Requirement

- Increase UT coverage to 80% (minimum) for core components  (excluding the [throttler](https://github.com/kata-containers/ksm-throttler) which is not well used afaik).

- Ensure the percentages stay at or above this threshold.

  This isn't quite as simple as it sounds: although it would be easy to mandate that every code PR includes a full set of unit tests that isn't always realistic. Some unit test scenarios are difficult to engineer (either technically difficult or extremely time-consuming to investigate). Sometimes we get "drive-by PRs" without tests, *etc*.

# Why?

Unfortunately, the current figures are not very good. They used to be a lot better, but the project has grown a lot and as a result the percentages have dropped.

| Component | UT coverage |
|-|-|
| runtime | 58.6% |
| throttler | 55.7% |
| agent | 50.1% |
| proxy | 40.0% |
| shim | 38.4% |

# Tasks

- [x] Fix CI UT data collection: https://github.com/kata-containers/tests/pull/1617.
- [ ] Write more tests (in priority order):
  - [ ] https://github.com/kata-containers/agent/issues/561
  - [ ] runtime
  - [ ] proxy
  - [ ] shim
- [ ] Update docs to explain how we handle UT coverage regressions.
- [ ] Ensure [codecov](https://codecov.io/gh/kata-containers) is working again.

# Strategy

- Phase 1: "tal"
  Investigate how much work adding new tests is going to be for each file / package / component.

- Phase 2: "jfdi"

  Divide the work up and give individual issues to team members to work on.

# Finally

The figures may be better for the runtime once we finish the slash'n'burn work on:

- https://github.com/kata-containers/runtime/issues/1113
- https://github.com/kata-containers/runtime/issues/1213
