### ISSUE TITLE
CCv0: Support signature verification with image-rs & the Offline filesystem KBC

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#4581]
## Background

At the moment the Red Hat container image signature verification of container images only works either with skopeo (following [these instructions](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md#verifying-signed-images) and tested with our CC integration tests), or using the attestation-agent with the EAA KBC (I've not tried this myself and we don't have automation to test it, but I think was it demoed on a CC call on 17th March 2022 and the recording for this is missing). As we move to the first release of CC, we want to remove skopeo from the rootfs image, which would result in us not having a local/offline attestation method of validating the signatures of images we pull and our CI tests failing.

The current state of testing of using image-rs with the `offline_fs_kbc` (which I think is the primary use case we want to test in our non-TEE pipeline) is that images with is that images with missing signatures are pulled and containers created from them:
```
$ export AA_KBC=offline_fs_kbc
$ ~/ccv0.sh build_and_install_all
...
$ ~/ccv0.sh copy_signature_files_to_guest
kata-containers/
kata-containers/confidential-containers/
kata-containers/confidential-containers@sha256=febcf61cd6e1ac9628f6ac14fa40836d16f3c6ddef3b303ff0321606e55ddd0b/
kata-containers/confidential-containers@sha256=febcf61cd6e1ac9628f6ac14fa40836d16f3c6ddef3b303ff0321606e55ddd0b/signature-1
kata-containers/confidential-containers@sha256=7250923ba3543110040462388756ef099331822c6172a050b12c7a38361ea46f/
kata-containers/confidential-containers@sha256=7250923ba3543110040462388756ef099331822c6172a050b12c7a38361ea46f/signature-1
$ ~/ccv0.sh crictl_create_cc_pod
...
POD ID              CREATED             STATE               NAME                      NAMESPACE           ATTEMPT             RUNTIME
e4717a7b19343       5 seconds ago       Ready               kata-cc-busybox-sandbox   default             0                   kata
$ export CONTAINER_CONFIG_FILE=container-config_unsigned-protected.yaml
$ ~/ccv0.sh crictl_create_cc_container
fc47ff243cdd456dd54f790a9c0623f2d282b6de75319d2ef340d1c7e179467d
CONTAINER           IMAGE                                                      CREATED                  STATE               NAME                       ATTEMPT             POD ID              POD
fc47ff243cdd4       quay.io/kata-containers/confidential-containers:unsigned   Less than a second ago   Running             kata-cc-busybox-unsigned   0                   e4717a7b19343       unknown
```
> **Note:** This behaviour is the same for using image-rs without any KBC, but I don't think that is a scenario we are worried about as it's not 'confidential' containers, and outside the scope of this issue.

When we have finished this issue, we'd expect this case to fail in a way similar to the skopeo set up does with a message to let the user know that the signature verification failed as it was missing.

The mechanism that the skopeo path currently uses to validate the container image signatures is:
- During testing we run [`copy_files_to_guest`](https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/lib.sh#L179-L191) which adds:
- The public GPG key that signed the images
- The policy file that links our test registry to the public GPG key  
- The signatures claim file(s) for the registry
- The registry configuration file that links our test registry to the signature location
to the guest image.

We then set `agent.container_policy_file=<policy file path>` as a kernel parameter to the guest image as agent configuration. In `image_rpc.rs`, when we pull the image with skopeo the policy path is passed into skopeo with the `--policy` flag. If we aren't using skopeo (the future state) this policy path is ignored.

From looking at the code in `image-rs` I think the current/future approach to signature validation is to get the required files using the [`get resource` endpoint](https://github.com/confidential-containers/image-rs/blob/main/docs/ccv1_image_security_design.md#get-resource-service) of the attestation agent. In [image-rs/src/validate.rs](https://github.com/confidential-containers/image-rs/blob/ec5f7c53f1860e64c883828ec4c84b03d9b7d123/src/validate.rs#L68) (if the policy file doesn't already exist) the policy_json is obtained from the `Policy` request to `get_resource_from_kbs` and this pattern is also used to get the `Sigstore Config` and `GPG keyring`.
> **Note:** I'm not sure what the process to get signature claim files into the guest filesystem is if that is required (i.e. the signature isn't hosted on a webserver and the registry doesn't support the `X-Registry-Supports-Signatures` API?), maybe just to copy the signature claim file into the rootfs like we do at the moment, but that has the limitation of having to edit the guest file system?

In order to trigger this code path the `ImageConfig` needs to be created with `security_validate` set to `true`. I guess we'd need to update the ImageClient creation code in [`image_rpc.rs`](https://github.com/kata-containers/kata-containers/blob/8f6eca517ab73f3f397288b7e4ead2455572586e/src/agent/src/image_rpc.rs#L55) to pass this in, maybe based on a setting in the Kata agent config?

## Task list

The work to add support for the get_resource interface to the `offline_fs_kbc` is covered under issue [confidential-containers/attestation-agent#63](https://github.com/confidential-containers/attestation-agent/issues/63) and once this has been completed, we'll need to make the updates on the kata-containers side. Depending on that implementation we might have to:
- [ ] Update our [code that injects the signature verification files into the rootfs](https://github.com/kata-containers/tests/blob/fdeb7215191f570a8120c64e28c739e89e6ffa4b/integration/confidential/lib.sh#L179-L191) (which should be renamed for clarity) to instead add them to the resource version of `aa-offline_fs_kbc-keys.json` as matching the attestation-agent implementation
- [ ] Work out the best way to enable the `ImageClient` to mandate signature verification, maybe based on the agent configuration and implement it? It would be good to understand how this was enabled for EAA in their e2e demo
- [ ] Update the signature verification tests to mandate signature verification in this way and switch them to not skip if skopeo isn't installed. The behaviour when an image is rejected is likely to have also changed slightly (different messages), so we'll need to update the tests to match that as well.
- [ ] Update the [CCv0 signature verification doc](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md#verifying-signed-images) to reflect that `export SKOPEO=yes` is not required (but the mandate signature verification config is).
- [ ] Remove the `container_policy_file` option from the [agent configuration code](https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/config.rs).

> **Note:** At the moment skopeo is still required for supporting encrypted container images, so until that is resolve (issue TBA), skopeo shouldn't be removed completely. Issue [kata-containers/kata-containers#3970](https://github.com/kata-containers/kata-containers/issues/3970) covers this work.

**Comment by stevenhorsman** [comment]
I've written initial prototype code for this, going through testing now...
