### ISSUE TITLE
CC: Create a better way to enable/disable signature verification when pulling images

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#4888]
**As a** confidential containers user
**I want to** be able to easily enable/disable the requirement for signature validation when pulling container images
**So that** I can ensure that my non encrypted container images have not been tampered with when I wish

## Description

With https://github.com/kata-containers/kata-containers/issues/4581 we should have a mechanism to get signature verification working and tested with image-rs through the kata-agent, but, we probably want to think a bit carefully about how we choose to enable/disable it.

My immediate suggestion for this would be to add a parameter (like `enable_signature_verification=true/false`), which defaults to false to the kata-agent's config, so it can be set in with the guest `kernel_params` in the kata-configuration, or the agent config file (e.g. agent-config.toml) to set whether this is on or off. I think should allow us to set this without requiring code changes and rebuilding separate versions of the guest image with different configurations, but we might need to think about this more carefully to get the user experience correct in future once we have a more holistic agent configuration strategy.

## Task list

- [x] Add a new field `enable_signature_verification` to the agent configuration, with a default to true
  - [x] Support reading this from `kernel_params` command line
  - [x] and reading from the agent-config file
  - [x] Add unit tests for this feature as appropriate
- [x] Update the kata-configuration templates to have this turned off in `kernel_params`, but maybe with a message explaining what it is?
- [x] Update `image_rpc.rs` to replace the current logic, and read this in from the agent config and flow the setting through to image-rs
- [x] Update the CI tests that do signature validation to enable the setting https://github.com/kata-containers/tests/issues/5228

## Acceptance Criteria

_**Scenario**: Ensure that signature validation isn't required with default settings_
**Given** I install kata CC (longer term via the operator, but short term building it locally) without any signature verification configuration
**When** I create a pod from a non-signed container image
**Then** The pull image works and the pod can start

_**Scenario**: Ensure the kata-configuration.toml setting is passed through to image-rs and a non-signed image is rejected_
**Given** I install kata CC (longer term via the operator, but short term building it locally) without any signature verification configuration and set `enable_signature_verfication=true` (or the final equivalent) in kata-configuration.toml 
**When** I create a pod from a non-signed container image
**Then** The pull image fails with a message that reflects that signature verification is required

_**Scenario**: Ensure the kata-configuration.toml setting is passed through to image-rs and a signed image is not rejected_
**Given** I install kata CC (longer term via the operator, but short term building it locally) and set `enable_signature_verfication=true` (or the final equivalent) in kata-configuration.toml and provide a valid signature verification configuration to the attestation agent/kbc
**When** I create a pod from a matching signed container image
**Then** The pull image works and the pod can start

**Comment by arronwy** [comment]
I also agree we can set in `kernel_params`  and the kernel cmdline will be measured.

Since it is a security feature, we may need enabled it by default to avoid misuse, but it will impact the user experience when user to try our CoCo stack without signature verification feature. Maybe we can enable in kata-agent by default, and disable it in kata `configuration.toml` file by default to make user aware this important configuration?

**Comment by stevenhorsman** [comment]
> Since it is a security feature, we may need enabled it by default to avoid misuse, but it will impact the user experience when user to try our CoCo stack without signature verification feature. Maybe we can enable in kata-agent by default, and disable it in kata `configuration.toml` file by default to make user aware this important configuration?

Yes, I think enabling by default makes sense. With the security settings is a tricky balance between trying to ensure that people who don't want the setting aren't inconvenienced, but that the defaults lean towards more secure so a user doesn't accidentally have the setting off without realising.
Something I'd like to test/understand is if `security_validate` is set to true, but get_resource doesn't have any content whether it defaults to reject everything, or acts like `"type": "insecureAcceptAnything"` as if it's the later then I think we should be safe to have the setting always on, but not for the former.

**Comment by Xynnn007** [comment]
> Something I'd like to test/understand is if `security_validate` is set to true, but get_resource doesn't have any content whether it defaults to reject everything, or acts like `"type": "insecureAcceptAnything"` as if it's the later then I think we should be safe to have the setting always on, but not for the former.

If `security_validate` is set to `true`, but no resources are got when calling `get_resource `, the image will be denied. It is because `get signature` is part of the verification of the signature.

> My immediate suggestion for this would be to add a parameter (like `enable_signature_verfication=true/false`), which defaults to false?

I agree that we temporarily add a parameter in kata-agent's config. However, in future if image-rs has more functions, IMO we should think about bring out all the related configurations into a separate config file, for image-rs. And this file will be pulled from the tenant side via RA and KBS. The process may look like:

init kata-agent / image-rs -> Do Remote Attestation and establish trusted channel between KBS and AA inside the Guest VM-> pull config via the trusted channel for image-rs -> start to serve `create container` requests

I don't know the details behind the behavior `create container` quite well, but I think this way there will be two benefits:
* Decoupling kata-agent and image-rs, the only thing kata-agent should do is create an `PullClient` and call relative functions.
* Let image-rs serve more scenarios where pulling signed/encrypted image is required, not just CC.

**Comment by stevenhorsman** [comment]
> I agree that we temporarily add a parameter in kata-agent's config. However, in future if image-rs has more functions, IMO we should think about bring out all the related configurations into a separate config file, for image-rs. And this file will be pulled from the tenant side via RA and KBS.

This sounds like a cool plan to me - we you thinking of adding the client configuration to the getresource endpoint, or introducing a new one? I think the key thing is that we'll probably get some of the interfaces and interactions a bit wrong to start with as we don't know quite how the scope of our requirements will grow, but given we are pre-1.0 release I think we can just try some things and then change them as necessary.
On of the things that I was thinking about trying to design/discuss soon is adding a new field to the getresource endpoint that returns credentials (maybe base64 encoded?) - then we can use that to let image-rs pull containers from authenticated registries. I'm not sure if overloading getresources is something we want to keep doing long term and I know we've talked about how we can support multiple container registries in future which might change the design, but I hope this plan might be a fairly easy way for us to extend our current process to get that extra bit of data in and support authenticated registries in the short term?

**Comment by Xynnn007** [comment]
> On of the things that I was thinking about trying to design/discuss soon is adding a new field to the getresource endpoint that returns credentials (maybe base64 encoded?) - then we can use that to let image-rs pull containers from authenticated registries. I'm not sure if overloading getresources is something we want to keep doing long term and I know we've talked about how we can support multiple container registries in future which might change the design, but I hope this plan might be a fairly easy way for us to extend our current process to get that extra bit of data in and support authenticated registries in the short term?

I'm not sure the meaning of the term `endpoint` here. I think we do not need add a new field to getresource en

**Comment by Xynnn007** [comment]
> On of the things that I was thinking about trying to design/discuss soon is adding a new field to the getresource endpoint that returns credentials (maybe base64 encoded?) - then we can use that to let image-rs pull containers from authenticated registries. I'm not sure if overloading getresources is something we want to keep doing long term and I know we've talked about how we can support multiple container registries in future which might change the design, but I hope this plan might be a fairly easy way for us to extend our current process to get that extra bit of data in and support authenticated registries in the short term?

I'm not sure about the meaning of the term `endpoint` here.
For the problem you've mentioned here, I think we can create new `ResourceDescription` request message like
```json
{
    "name": "credential",
    "optional": {
        "registry": "...",
    },
}
```

following the definition of `ResourceDescription` in AA https://github.com/confidential-containers/attestation-agent/blob/79592180736a6009086040b63b5424e86e330e83/src/kbc_modules/mod.rs#L133

And then as you said, the credential will be sent from KBS in base64 encoded.

The key point is that this channel, between KBS and AA (kbc inside), is the only trusted channel that can be used to transfer secrets from the tenant side, thus overloading get_resource interface is something we surely want to keep doing long term, because we do not need to establish another channel, it can be redundant.

Besides, a naive question from me: how the image-rs can know that "this registry needs credential"?

**Comment by stevenhorsman** [comment]
> I'm not sure about the meaning of the term `endpoint` here. For the problem you've mentioned here, I think we can create new `ResourceDescription` request message like
> 
> ```json
> {
>     "name": "credential",
>     "optional": {
>         "registry": "...",
>     },
> }
> ```
> 
> following the definition of `ResourceDescription` in AA https://github.com/confidential-containers/attestation-agent/blob/79592180736a6009086040b63b5424e86e330e83/src/kbc_modules/mod.rs#L133

Yes, sorry if I've got my terminology mixed up here. What a meant was another payload option for credentials similar to how we can serve `GPGPublicKey`/`Policy` etc at the moment.

> And then as you said, the credential will be sent from KBS in base64 encoded.
> 
> The key point is that this channel, between KBS and AA (kbc inside), is the only trusted channel that can be used to transfer secrets from the tenant side, thus overloading get_resource interface is something we surely want to keep doing long term, because we do not need to establish another channel, it can be redundant. How do you think about this?

I agree that the trusted channel is the correct way, but I wasn't sure if having more formalised proto messages along this channel might be easier for people to consume and understand, but I might have misunderstood how it is currently working.

> Besides, a naive question from me: how the image-rs can know that "this registry needs credential"?

It's not a naive question as there isn't necessarily a simple answer. There are obviously some registries that a completely public (like quay.io/confidential-containers repo we are using for the test images), some that are private and you can't get anything without credentials and then a gray area of things in between. For example any public repo in docker hub can be accessed without credentials, but as an anonymous IP you are limited to (~100 IIRC) requests a month, and after that need to log in to get more, so good get into a state that you can pull anonymously sometimes, not then get rejected later.
I think the best approach is to continue the logic we have in image-rs at the moment: Default to `let mut auth = RegistryAuth::Anonymous;` and credentials aren't mandatory, but we can attempt the get_resource request to try and get them and if they are supplied then we configure registry auth based on then. 

BTW - sorry that I took us completely off topic in this issue and we've ended up talking more about https://github.com/kata-containers/kata-containers/issues/4601 here! To cycle back to the original point - I think having a setting available in `kata_configuration.toml` is fine for the short term, but like the idea of being able to decouple the configuration. As long as we can support it in the offline_fs_kbc then I think that shouldn't negatively impact the non-TEE CI tests and user scenarios we have at the moment.

**Comment by wainersm** [comment]
Hi Steve, very detailed plan as always! 
 
> My immediate suggestion for this would be to add a parameter (like `enable_signature_verfication=true/false`), which defaults to false to the kata-agent's config, so it can be set in with the guest `kernel_params` in the kata-configuration, or the agent config file (e.g. agent-config.toml) to set whether this is on or off. I think should allow us to set this without requiring code changes and rebuilding separate versions of the guest image with different configurations, but we might need to think about this more carefully to get the user experience correct in future once we have a more holistic agent configuration strategy.

Double-checking I understood: there will be a property on kata configuration.toml as well. So the users will have three possibilities to set on/off:

1. In the agent-config.toml which path is passed via `kernel_params`. In this case the file should be inject in the guest image.
2. Directly via `kernel_params`, e.g., `kernel_params="agent.enable_signature_verfication=true"`
3. Directly via a property on kata's `configuration.toml`

Please, see my https://github.com/kata-containers/kata-containers/issues/5173#issuecomment-1252919005 regarding passing parameters to the agent via properties in kata's `configuration.toml` vs `kernel_params`

Apart from that, do this signature verification property *must* be part of the measurements for the attestation process?

**Comment by stevenhorsman** [comment]
> Hi Steve, very detailed plan as always!
> 
> > My immediate suggestion for this would be to add a parameter (like `enable_signature_verfication=true/false`), which defaults to false to the kata-agent's config, so it can be set in with the guest `kernel_params` in the kata-configuration, or the agent config file (e.g. agent-config.toml) to set whether this is on or off. I think should allow us to set this without requiring code changes and rebuilding separate versions of the guest image with different configurations, but we might need to think about this more carefully to get the user experience correct in future once we have a more holistic agent configuration strategy.
> 
> Double-checking I understood: there will be a property on kata configuration.toml as well. So the users will have three possibilities to set on/off:
> 
> 1. In the agent-config.toml which path is passed via `kernel_params`. In this case the file should be inject in the guest image.
> 2. Directly via `kernel_params`, e.g., `kernel_params="agent.enable_signature_verfication=true"`
> 3. Directly via a property on kata's `configuration.toml`

Sorry, I wasn't clear here. I would only intend to implement 1 & 2 here at the moment, to line up with the other agent configuration options.

> Please, see my [#5173 (comment)](https://github.com/kata-containers/kata-containers/issues/5173#issuecomment-1252919005) regarding passing parameters to the agent via properties in kata's `configuration.toml` vs `kernel_params`
> 

Yes, I agree that we want to do a proper review of agent configuration and decide what need to be measured and whether we should add them into the `[agent]` section of the kata-configuration rather than just adding to `kernel_params`, but I'd like to do that review on everything, which would be outside the scope of this issue.

> Apart from that, do this signature verification property _must_ be part of the measurements for the attestation process?

I'm not sure on this. I think that if it isn't measured there is a danger that a kubernetes admin could turn it off and the workload provider wouldn't be able to stop them switching out a non-encrypted, but signed container image in the workload. There might be a better scenario here, but maybe they could then swap something like an istio sidecar container for their own that sniffs around for secrets? I'm not so great on the Trusted model stuff, so I'd prefer this setting to be part of the larger review I mention earlier in this comment.

**Comment by stevenhorsman** [comment]
Closed with #5552 merging
