### ISSUE TITLE
CC: Remove skopeo and umoci from the operator deploy payload image

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#4889]
Once we have support for signature verification without skopeo in Kata CC (either after https://github.com/kata-containers/kata-containers/issues/4888, or https://github.com/kata-containers/kata-containers/issues/4581) and have all the CC integration tests working without the requirement for skopeo and umoci, we should either set `skopeo=no` & `umoci=no` (or more likely just removing those variables) in [kata-deploy-binaries.sh](https://github.com/kata-containers/kata-containers/blob/72691ed6afcfaf426ac75a3f87aab3750b85087f/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L114), so they won't get built into the operator’s cc guest image, but without removing them from the code base completely.

This would allow us to test both skopeo and image-rs for the short-term and compare results and also allow people who want to things that image-rs doesn’t support yet (such as authenticated registries) to keep using skopeo for a little bit longer until the gaps have been fully closed, but satisfy the concern of having the big binaries in the operator payload being removed for the release.

## Task List
- [x] Update the CC deploy script in `kata-deploy-binaries.sh` to stop skopeo and umoci being build
- [x] Update the operator test to not `export SKOPEO=yes`
- [x] Using the [doc](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-generate-a-kata-containers-payload-for-the-confidential-containers-operator.md) run the deploy process locally to make the payload image
  - [x] Test deploying this image and validate that skopeo and umoci are not in the resulting guest that is created for a container
- [x] Get the PR merged

## Acceptance Criteria

**Given** I have a Kubernetes cluster
**When** I run the 'co-co' operator against it
**Then** the Kata CC runtime and dependencies are deployed and it is enabled for Kata CC workloads

**Given** I have a Kata CC enabled Kubernetes cluster
**When** I deploy a kata-CC runtime workload
**Then** the pod starts correctly and if I exec into it I can check that skopeo & umoci are not installed.

**Comment by stevenhorsman** [comment]
I've create a [PR](https://github.com/kata-containers/kata-containers/pull/5202) to remove skopeo and umoci from the deploy image and kicked off the deploy image creation with:
```
git clone --branch remove-skopeo-from-deploy https://github.com/stevenhorsman/kata-containers.git
cd kata-containers/
sudo docker login quay.io
sudo make cc-payload
```
After 2h17m this finished and we have a new image in quay.io: kata-containers-77176cd7b94ec1a8c7afba08e246e84ca21cd161 
Tomorrow I plan to update the operator code to pick up this latest payload and disable skopeo from the testing and see if that PR works.

**Comment by stevenhorsman** [comment]
This work has been done under PR [https://github.com/kata-containers/kata-containers/pull/5202](https://github.com/kata-containers/kata-containers/pull/5202), and issues https://github.com/kata-containers/kata-containers/issues/5237 & [confidential-containers/operator#87](https://github.com/confidential-containers/operator/issues/87), so I believe is closed now
