### ISSUE TITLE
Tracking issue for issue backlog work

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#512]
This issue is used to track improvements to the issue backlog project board [1].

- [x] - [Create GitHub project for issue backlog tracking](https://github.com/orgs/kata-containers/projects/23).
- [x] Add all open issues *in all repos* to the project's "To do" column.

     "Done" using a [`hub`](https://github.com/github/hub) script I've written. However, this script will need to be run repeatedly until we have automation in place to handle this when new issues are raised.
- [x] Add hub extension tool to control GitHub projects via the CLI

  https://github.com/kata-containers/.github/pull/10

  This can be used by GitHub actions to manage project boards.

- [x] Add automation to automatically add newly created issues *in all repos* to the "To do" column.

   See table below.

- [x] Add automation to automatically move issues from the "To do" column to the "In progress" column when a linked PR is raise.

   See table below.

# Actions to add

Summary of PRs covering the actions we need to add:

| Repo | PR |
|-|-|
| ~~`agent`~~ | ~~https://github.com/kata-containers/agent/pull/826~~ |
| ~~`ci`~~ | ~~https://github.com/kata-containers/ci/pull/321~~ |
| ~~`community`~~ | ~~https://github.com/kata-containers/community/pull/167~~ |
| ~~`documentation`~~ | ~~https://github.com/kata-containers/documentation/pull/724~~<br/>~~https://github.com/kata-containers/documentation/pull/733~~ |
| `kata-containers` | https://github.com/kata-containers/kata-containers/pull/711 |
| ~~`ksm-throttler`~~ | ~~https://github.com/kata-containers/ksm-throttler/pull/164~~ |
| ~~`osbuilder`~~ | ~~https://github.com/kata-containers/osbuilder/pull/495~~ |
| ~~`packaging`~~ | ~~https://github.com/kata-containers/packaging/pull/1130~~ |
| ~~`proxy`~~ | ~~https://github.com/kata-containers/proxy/pull/274~~<br/>~~https://github.com/kata-containers/proxy/pull/281~~ |
| ~~`runtime`~~ | ~~https://github.com/kata-containers/runtime/pull/2911~~ |
| ~~`shim`~~ | ~~https://github.com/kata-containers/shim/pull/267~~ |
| ~~`tests`~~ | ~~https://github.com/kata-containers/tests/pull/2819~~ |
| ~~`www.katacontainers.io`~~ | ~~https://github.com/kata-containers/www.katacontainers.io/pull/115~~<br/>~~https://github.com/kata-containers/www.katacontainers.io/pull/121~~ |

References:

- http://lists.katacontainers.io/pipermail/kata-dev/2020-August/001412.html
- http://lists.katacontainers.io/pipermail/kata-dev/2020-August/001424.html
- http://lists.katacontainers.io/pipermail/kata-dev/2020-August/001434.html

---
[1] - yeah, yeah, we could create yet-another-GitHub-project for this but... :smile:

**Comment by jodh-intel** [comment]
Removed `do-not-merge` label from the other PRs now that https://github.com/kata-containers/proxy/pull/274 has landed.

**Comment by jodh-intel** [comment]
Closing as all child PRs are now merged.

/cc @ariel-adam.
