### ISSUE TITLE
Implement fully featured Cloud Hypervisor runtime-rs hypervisor plugin

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6263]
Remaining tasks:

- [ ] [Implement initial basic MVP](https://github.com/kata-containers/kata-containers/issues/5242)
- [ ] [Implement `Persist` trait](https://github.com/kata-containers/kata-containers/issues/6202)
- [ ] [Implement format conversion](https://github.com/kata-containers/kata-containers/issues/6203)
- [ ] [Fix slow shutdown](https://github.com/kata-containers/kata-containers/issues/6204)

Related: #4634.
