### ISSUE TITLE
merge-to-main: Integrate and test guest-components into confidential image

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#9058]
This is a placeholder issue that summarises the work that has to be done in order to get the guest components tests with our CI
A breakdown of the issues goes as follow:
* [x] - [Make `add_kernel_initrd_annotations_to_yaml` generic](https://github.com/kata-containers/kata-containers/issues/9054)
* [x] - [Add the ability to run (some of the) confidential tests in non-TEE environments](https://github.com/kata-containers/kata-containers/issues/9055)
* [x] - [Deploy the Confidential Containers KBS as part of the confidential tests](https://github.com/kata-containers/kata-containers/issues/9056)
* [ ] -[ Add a test for the guest components integration](https://github.com/kata-containers/kata-containers/issues/9057)

There may be more details needed as part of #9056 and #9057, and I'd like to ask folks to take a look at those and add more details whenever they feel like it's needed.
