### ISSUE TITLE
CC: Enable guest-components tests for AMD SEV

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#9376]
### Context

On [port attestation agent from CCv0 branch to main branch](https://github.com/kata-containers/kata-containers/pull/8870) we introduce the last bits of attestation on non-TEE environments, including tests. The follow on should be to add support on TEE environments (SEV, SNP, TDX).

### Details

AMD SEV is a particular case because it should still be implemented some features on runtime, for example, [sev: add sev support to kata-shim (main)](https://github.com/kata-containers/kata-containers/issues/6571). Apart from that, testing will be slightly different because on SEV it uses [simple-kbs](https://github.com/confidential-containers/simple-kbs) (and the `online_sev_kbc` KBC).

This issue tracks the work required to enable tests on CI for attestation.

Depends on:
- [x] [port attestation agent from CCv0 branch to main branch](https://github.com/kata-containers/kata-containers/pull/8870)
- [ ] [sev: add sev support to kata-shim (main)](https://github.com/kata-containers/kata-containers/issues/6571) 

### Work breakdown

- [ ] Add support for simple-kbs in [confidential_kbs.sh](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/confidential_kbs.sh) lib
- [ ] Change the [run-k8s-tests-on-sev](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/run-kata-coco-tests.yaml#L80) workflow to install simple-kbs
- [ ] Change the attestation test to proper configure simple-kbs and use `offline_sev_kbc`

### Additional resources

[1] [simple-kbs utility functions on CCv0](https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/lib.sh#L360)

Cc @ryansavino @fitzthum @AdithyaKrishnan

**Comment by stevenhorsman** [comment]
SEV has been removed now
