### ISSUE TITLE
CC: Enable guest-components tests for AMD SNP

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#9378]
### Context

On [port attestation agent from CCv0 branch to main branch](https://github.com/kata-containers/kata-containers/pull/8870) we introduce the last bits of attestation on non-TEE environments, including tests. The follow on should be to add support on TEE environments (SEV, SNP, TDX).

### Details

Testing for AMD SNP should be pretty similar to non-TEE. It requires same CoCo's KBS and `cc_kbc` KBC.

Likewise [SEV](https://github.com/kata-containers/kata-containers/issues/9376) it will be needed some features not yet implemented on runtime. 

This issue tracks the work required to enable tests on CI for attestation.

Depends on:

- [x] [port attestation agent from CCv0 branch to main branch](https://github.com/kata-containers/kata-containers/pull/8870)
- [ ] [Fix SNP extended attestation with latest AMD kernel/qemu patches](https://github.com/kata-containers/kata-containers/issues/9101)
- [x] [runtime: enable kernel-hashes for SNP confidential container](https://github.com/kata-containers/kata-containers/pull/9151)
- [x] [tests: strengthen kbs_k8s_delete() for baremetal](https://github.com/kata-containers/kata-containers/issues/9379) 

### Work breakdown

- [x] [tests: Support for kbs setup on kcli](https://github.com/kata-containers/kata-containers/pull/9273) - This same KBS setup should work on SNP with kubeadm 
- [x] Change the [run-k8s-tests-on-snp](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/run-kata-coco-tests.yaml#L135) workflow to install KBS
- [x] Enable the attestation test to run on jobs with `qemu-snp` hypervisor.

Cc @ryansavino @fitzthum @AdithyaKrishnan

**Comment by wainersm** [comment]
https://github.com/kata-containers/kata-containers/pull/9273 was merged but it wasn't tested with kubeadm. I really believe it will work out; we will see when try to enable guest-components tests on SNP.

**Comment by ariel-adam** [comment]
@wainersm should we leave this in 0.9.0 or move it to 0.10.0?

**Comment by wainersm** [comment]
> @wainersm should we leave this in 0.9.0 or move it to 0.10.0?

@ariel-adam the runtime is still not ready for SNP attestation. I will let @ryansavino @fitzthum answers if they want it for 0.9 or 0.10.

From CI/test point of view, the code is ready, it would need to just enable for snp and fingers crossed it will work.

**Comment by wainersm** [comment]
We managed to complete this work in time for 0.9.0. Thanks to @niteeshkd @ryansavino @AdithyaKrishnan @fitzthum and everyone that helped on moving this forward!
