### ISSUE TITLE
 CC: Enable guest-components tests for Intel TDX

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#9394]
### Context

On [port attestation agent from CCv0 branch to main branch](https://github.com/kata-containers/kata-containers/pull/8870) we introduce the last bits of attestation on non-TEE environments, including tests. The follow on should be to add support on TEE environments (SEV, SNP, TDX).

### Details

Testing for Intel TDX should be pretty similar to non-TEE. It requires same CoCo's KBS and `cc_kbc` KBC.

This issue tracks the work required to enable tests on CI for attestation.

Depends on:

- [x] [port attestation agent from CCv0 branch to main branch](https://github.com/kata-containers/kata-containers/pull/8870)
- [x] [tests: strengthen kbs_k8s_delete() for baremetal](https://github.com/kata-containers/kata-containers/issues/9379) 

### Work breakdown

- [x] [tests: Support for kbs setup on kcli](https://github.com/kata-containers/kata-containers/pull/9273) - This same KBS setup should work on TDX with k3s
- [x] Change the [run-k8s-tests-on-tdx](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/run-kata-coco-tests.yaml#L26) workflow to install KBS
- [x] Enable the attestation test to run on jobs with `qemu-tdx` hypervisor.

Cc @GabyCT @fidencio

**Comment by GabyCT** [comment]
Thanks @wainersm for putting this together, I will discuss with @fidencio if there is something else that we will need for TDX

**Comment by wainersm** [comment]
Thanks @GabyCT for checking that https://github.com/kata-containers/kata-containers/pull/9273 works with k3s; so one step closer to get the guest-components tests running on TDX.

**Comment by wainersm** [comment]
Done. Thanks @GabyCT @fidencio !
