### ISSUE TITLE
Enable guest-pull tests for non-TEE for s390x

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#9467]
**Which feature do you think can be improved?**

In line with #9424, it is time to enable the guest-pull test for non-TEE for s390x. We do have confidential artifacts (kernel, image and initrd) for the platform. This issue is to summarise some of the environmental adjustment required for the enablement. They were identified during the testing trials as follows:

- [x] Kernel 6.7 should be compiled: https://github.com/kata-containers/kata-containers/issues/9465
- [x] Configure a coco name and version for {image,initrd} https://github.com/kata-containers/kata-containers/issues/9470
- [x] OPA should be built from the source: https://github.com/kata-containers/kata-containers/issues/9466

Further issues could be added to this issue as the enablement goes on.
