### ISSUE TITLE
Initdata Implementation

### ISSUE THREAD

**Issue by Xynnn007** [kata-containers/kata-containers#9468]
**Which feature do you think can be improved?**

This issue tracks kata side implementations of [initdata injection](https://github.com/confidential-containers/confidential-containers/issues/171). cc @arronwy 

The core idea of initdata is to leverage attestation cover the configurations of guest-components and policy.

**Preliminary Work**
- [x] Technical way choice: configuration files and rego policy should be well-defined keys inside initdata TOML due to https://docs.google.com/document/d/1vrhIY2Br_r4yM-8iSU8XFm0DImrwmQsycaBnZzV43wE/edit#heading=h.fn2nl15pagr . 
- [x] Concrete Initdata Spec: https://github.com/confidential-containers/trustee/pull/348
- [x] Configuration files for AA, CDH: https://github.com/confidential-containers/guest-components/pull/531 https://github.com/confidential-containers/guest-components/pull/444
- [x] CheckInitData API of AA: https://github.com/confidential-containers/guest-components/pull/462

**TODO list**
- [ ] `kata-runtime` side: support get initdata yaml from pod yaml, calculate the digest of the initdata and set it as the concrete TEE's hostdata field.
- [ ] `kata-agent` side: extend SetPolicy to SetInitdata API, receive initdata yaml from host, check the integrity binding and then set guest-components' config and policy. This will rise a problem about the launch order:
1. If we have already launched them before the kata-agent serves `SetInitData` API, when we get `SetInitData` request we should call something like `UpdateConfiguration()` API for them. This seems redundant. 
2. If we have not launched them before the kata-agent serves `SetInitData` API, we need to launch them right after `SetInitData` using given configurations. The question is what if no `SetInitData` API call happens?

To handle this, another high level design way is to directly implement @huoqifeng 's https://github.com/confidential-containers/confidential-containers/issues/171#issuecomment-1922821565 design. But in this way, systemd and a new component are required. The new component runs before kata-agent to verify initdata digest binding and to put configurations of guest components to known path. We need some discussion and converge into a final design here.
- [ ] e2e test for initdata injection.

cc @sameo @fitzthum @fidencio @stevenhorsman @danmihai1

**Comment by danmihai1** [comment]
My preferences, starting with the highest preference:

1. Keep SetPolicy in place but change it to use the new Init Data.
2. Rename SetPolicy to SetInitData and change it to use the new Init Data.

Either I or one of my colleagues might be able to help with the implementation if the changes above, if you guys want.

BTW, as I mentioned in a community meeting, I hope that we'll be able to replace in the Kata Agent the functionality of the OPA daemon with the Regorus crate, soon. I am currently working on that. If I will succeed, we should be able to initialize the Policy module of the Kata Agent even earlier than it gets initialized nowadays.

**Comment by Xynnn007** [comment]
> My preferences, starting with the highest preference:
> 
> 1. Keep SetPolicy in place but change it to use the new Init Data.
> 2. Rename SetPolicy to SetInitData and change it to use the new Init Data.
> 
> Either I or one of my colleagues might be able to help with the implementation of the changes above, if you guys want.
> 
> BTW, as I mentioned in a community meeting, I hope that we'll be able to replace in the Kata Agent the functionality of the OPA daemon with the Regorus crate, soon. I am currently working on that. If I will succeed, we should be able to initialize the Policy module of the Kata Agent even earlier than it gets initialized nowadays.

Nice. Let me ensure that there are three steps
1. Keep `SetPolicy` endpoint and support InitData also -- not break any existing paths
2. Rename `SetPolicy` to `SetInitData` and change it to use the new Init Data -- transform to initdata
3. \* Add `UpdatePolicy` API which is used in some cases. This API can be blocked in the first policy delivered by `SetInitData`. And this would also call AA's `extend_runtime_measurement` to record the event if in CoCo case

In near future, we can implement this in the following diagram

![image](https://github.com/kata-containers/kata-containers/assets/22250460/78b64106-bb7e-4da7-b080-28caeab2a6c8)

Note I marked OPA as dot background, it may involve Regorus integration.

We can start to discuss about final shape when we reach near future architecture.

wdyt?

**Comment by danmihai1** [comment]
Thanks @Xynnn007!

I will provide more feedback after I find time to think more about this - hopefully in the next days.

At a quick look, your plan above seems good to me! Some initial thoughts:


>> A (probably huge) PR that supports InitData in SetPolicy and go through the all path inside runtime & kata-agent.

Let's add a new SetInitData request that internally calls the older SetPolicy code path, in addition to performing other Init Data duties.

We can kill the SetPolicy ttrpc request later - unless we'll find good reasons to keep it. Currently, I am not aware of good reasons to keep the old SetPolicy for the longer term.

Maybe this is what you meant too above - I am just trying to clarify, to be sure we are on the same page.


>> some tests using initdata are passed

Depending on the interest in the community, changing the genpolicy tool to support Init Data and leveraging modified SetPolicy/genpolicy tests might help here.


>> Add UpdatePolicy API that could be controlled by the first policy injected via SetPolicy

I am also not aware of good reasons to add UpdatePolicy - let's discuss the use cases someday.


>> change SetPolicy to SetInitData

I would rename this step to "kill the old SetPolicy and keep just the new SetInitData - unless we'll find good reasons to keep SetPolicy".

**Comment by Xynnn007** [comment]
> Those steps look good to me. I'm not sure number 5 is required at first and I think it would only be supported on platforms with runtime measurement, right?

> I am also not aware of good reasons to add UpdatePolicy - let's discuss the use cases someday.

There are some scenarios that users wants to update the policy after launching the pod for a while. Hopefully we can get some agreement here after some introduction or discussion. cc @arronwy @ChengyuZhu6

**Comment by danmihai1** [comment]
@Xynnn007 I just wanted to:
- Confirm that the plan we discussed above still looks reasonable to me
- Let you know that the OPA daemon is no longer used in the Kata main branch - we are using the regorus crate instead (since merging https://github.com/kata-containers/kata-containers/pull/9510 yesterday)

**Comment by Xynnn007** [comment]
> @Xynnn007 I just wanted to:
> 
> * Confirm that the plan we discussed above still looks reasonable to me
> * Let you know that the OPA daemon is no longer used in the Kata main branch - we are using the regorus crate instead (since merging [agent: use regorus instead of opa #9510](https://github.com/kata-containers/kata-containers/pull/9510) yesterday)

Thanks. I am now trying to code, and the `set_policy` API does not change which is cool. Anyway, let's talk in that PR then.
