### ISSUE TITLE
Future planning: Handling deprecation and eventual EOL of Kata 1.x

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#966]
# Intro

*At some point* (not yet folks! :smile:), we will stop maintaining the [Kata Containers 1.x releases](https://github.com/kata-containers/runtime/releases).

We need to plan *how* that is going to be handled though. This issue is for tracking the required tasks.

# Tasks

- [ ] Decide how long we will support the 1.x stable branches (see #956).
- [ ] Start sending emails to the [public mailing list](http://lists.katacontainers.io/pipermail/kata-dev/) (every month?) showing the final dates, warnings, and 2.x migration details.
- [ ] Eventually send out a final email to the public ML stating that the last 1.x stable release is now unmtaintained.
- [ ] Signal that 1.x is no longer being maintained:
  - [ ] Archive the 1.x GitHub repos (+ change the top-level `README.md`'s to state the project is now unmaintained and provide links to the 2.x repo):
     - [ ] [agent](https://github.com/kata-containers/agent)
     - [ ] [documentation](https://github.com/kata-containers/documentation)
     - [ ] [ksm-throttler](https://github.com/kata-containers/ksm-throttler)
     - [ ] [osbuilder](https://github.com/kata-containers/osbuilder)
     - [ ] [packaging](https://github.com/kata-containers/packaging)
     - [ ] [proxy](https://github.com/kata-containers/proxy)
     - [ ] [runtime](https://github.com/kata-containers/runtime)
     - [ ] [shim](https://github.com/kata-containers/shim)
  - [ ] Forcibly breaking the [OBS repo](http://download.opensuse.org/repositories/home:/katacontainers:/releases:/) by either removing or disabling it.

Breaking the repo is potentially contentious but is the only way to avoid users believing they are "connected" to a source of regular updates when in fact they won't be (any longer). This will be painful for some, but the safest approach I think.

Related:

- https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/Upgrading.md#maintenance-warning
- https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/Stable-Branch-Strategy.md
- https://github.com/kata-containers/kata-containers/issues/956

/cc @kata-containers/architecture-committee, @gnawux, @amshinde.

**Comment by amshinde** [comment]
There are a few tasks that need to be completed to ensure parity with 1.x in terms of stability
 - Tests that test 100 docker images need to be run with 2.0 branch
 - We ran scalability tests in the past with 1.x running 500-1000 containers in a k8s cluster and with docker. These need to be  completed with 2.x as well. We could add this as a nightly/weekly test

We need to encourage customers using 1.x in production to evaluate 2.0 at some point and get feedback. This could be a user survey that we can set up.

**Comment by jodh-intel** [comment]
- Issue for porting the "top 100 docker images" tests to 2.x + containerd: https://github.com/kata-containers/tests/issues/2955.

**Comment by amshinde** [comment]
@chavafg @GabyCT Please add any comments here regarding missing test coverage for 2.0.

**Comment by jodh-intel** [comment]
Hi @fidencio, regarding http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001897.html, the script is [`hub-util.sh`](https://github.com/kata-containers/.github/tree/master/scripts) in the not-that-well-known [`.github`](https://github.com/kata-containers/.github) _repository_ :smile:.

To close the 1.x issues per repo, we can do this (here using the `runtime` repo as an example):

```bash
$ export slug="kata-containers/runtime"
$ export PATH="$PATH:$GOPATH/src/github.com/kata-containers/.github/scripts"
$ export comment_file="/tmp/comment.txt"
$ cd "$GOPATH/src/github.com/$slug"
$ hub issue | awk '{print $1}' | tr -d '#' | sort -n | while read issue
do
    hub-util.sh add-issue-comment "$issue" "$slug" "$comment_file"
    hub issue update "$issue" -s closed
done
```

For the contents of `$comment_file`, what do we all think about the following?

---

This issue is being automatically closed as Kata Containers 1.x has now reached EOL (End of Life). This means it is **no longer being maintained**.

> **Important:**
>
> All users should switch to the latest [Kata Containers 2.x release](https://github.com/kata-containers/kata-containers/blob/main/docs/install/README.md) to ensure they are using a maintained release that contains the latest security fixes, performance improvements and new features.

If you believe this issue still applies to Kata Containers 2.x, please re-open it and provide details to allow us to migrate the issue to the [Kata Containers 2.x repository](https://github.com/kata-containers/kata-containers).

---

**Comment by fidencio** [comment]
> Hi @fidencio, regarding http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001897.html, the script is [`hub-util.sh`](https://github.com/kata-containers/.github/tree/master/scripts) in the not-that-well-known [`.github`](https://github.com/kata-containers/.github) _repository_ smile.
> 
> To close the 1.x issues per repo, we can do this (here using the `runtime` repo as an example):
> 
> ```shell
> $ export slug="kata-containers/runtime"
> $ export PATH="$PATH:$GOPATH/src/github.com/kata-containers/.github/scripts"
> $ export comment_file="/tmp/comment.txt"
> $ cd "$GOPATH/src/github.com/$slug"
> $ hub issue | awk '{print $1}' | tr -d '#' | sort -n | while read issue
> do
>     hub-util.sh add-issue-comment "$issue" "$slug" "$comment_file"
>     hub issue update "$issue" -s closed
> done
> ```
> 
> For the contents of `$comment_file`, what do we all think about the following?
> 
> This issue is being automatically closed as Kata Containers 1.x has now reached EOL (End of Life). This means it is **no longer being maintained**.
> 
> > **Important:**
> > All users should switch to the latest [Kata Containers 2.x release](https://github.com/kata-containers/kata-containers/blob/main/docs/install/README.md) to ensure they are using a maintained release that contains the latest security fixes, performance improvements and new features.

I'd add that it was announced via our kata-dev mailing lists, adding the links to:
* http://lists.katacontainers.io/pipermail/kata-dev/2020-November/001601.html
* http://lists.katacontainers.io/pipermail/kata-dev/2021-April/001843.html
* http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001896.html

> 
> If you believe this issue still applies to Kata Containers 2.x, please re-open it and provide details to allow us to migrate the issue to the [Kata Containers 2.x repository](https://github.com/kata-containers/kata-containers).

This is not possible.  Once a repo is archived, it becomes read-only and the issues and pull-requests cannot be edited in any way.  So, I sincerely think we should recommend users to open new issues against [Kata Containers 2.x repository](https://github.com/kata-containers/kata-containers) pointing to the old ones and, if needed, we can do the un-archive, transfer, archive again dance.

**Comment by fidencio** [comment]
So, what about ....


---

This issue is being automatically closed as Kata Containers 1.x has now reached EOL (End of Life). This means it is **no longer being maintained**.

> **Important:**
>
> All users should switch to the latest [Kata Containers 2.x release](https://github.com/kata-containers/kata-containers/blob/main/docs/install/README.md) to ensure they are using a maintained release that contains the latest security fixes, performance improvements and new features.

This decision was discussed by the @kata-containers/architecture-committee and has been announced via the [Kata Containers mailing list](http://lists.katacontainers.io/pipermail/kata-dev/):
* http://lists.katacontainers.io/pipermail/kata-dev/2020-November/001601.html
* http://lists.katacontainers.io/pipermail/kata-dev/2021-April/001843.html
* http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001896.html

If you believe this issue still applies to Kata Containers 2.x, please open an issue against the [Kata Containers 2.x repository](https://github.com/kata-containers/kata-containers), pointing to this one, providing details to allow us to migrate it.
---

**Comment by jodh-intel** [comment]
Yep - I realised as soon as I'd put this comment on that when we archive ;)

**Comment by jodh-intel** [comment]
lgtm ;)

**Comment by fidencio** [comment]
@jodh-intel, there's a small issue that I just noticed, there's no `add-issue-comment` in the hub-util.sh script: https://github.com/kata-containers/.github/blob/376459c9045e06715e222173c1b02c6b04e11717/scripts/hub-util.sh#L887-L899

**Comment by jodh-intel** [comment]
Apologies @fidencio ! I'd forgotten that I hadn't raised a PR for that! Here it is:

- https://github.com/kata-containers/.github/pull/34

**Comment by fidencio** [comment]
Well, this one can be closed as 1.x reached its EOL.
